### ISSUE TITLE
Date is uploading to influx incorrectly

### ISSUE THREAD

**Issue by ShaneHudson** [myriadrf/limescan-device#1]
The month appears to be uploading as the month earlier (ie. June instead of July). The rest of the date/time is correct.

**Comment by ShaneHudson** [comment]
This appears to be a bug in https://github.com/myriadrf/lime-tools

**Comment by 9600** [comment]
Can you log an issue there please.

**Comment by ShaneHudson** [comment]
https://github.com/myriadrf/lime-tools/issues/7
