### ISSUE TITLE
Needs to get start and stop frequency etc. config from server.

### ISSUE THREAD

**Issue by 9600** [myriadrf/limescan-device#4]
Device should be getting the start/stop frequency and antenna etc. parameters from the configuration DB and not using hardcoded values.

For simplicity sake to start with it probably makes sense to just get the full parameter set via the Custom Config field. E.g.

"-f 600M:1000M -C 0 -A LNAW -w 35M -r 16M -OSR 8 -b 512 -g 48 -n 64 -O 'scan-output' -T 1"

We can later rework this so that as much as possible is set automatically, e.g. optimal -A setting will be frequency dependant. With the rest set via friendlier options in the UI.

**Comment by ShaneHudson** [comment]
The device now takes the parameter set in custom_config and uses that. -O is overrided so the output is correct.
