### ISSUE TITLE
Use a more meaningful DB name.

### ISSUE THREAD

**Issue by 9600** [myriadrf/limescan-device#6]
It's still not clear to me whether there would be benefit to having multiple DBs and e.g. one for LimeScan/LimeMon (power spectrum scans) data and another for LTE cell info.

But if for now if we keep it simple and instead of "limemicro" can use "limescan-prod".

**Comment by ShaneHudson** [comment]
Just wondering what your reason is for this? If we do this then currently (without a code change) it would need updating to switch between production and staging. Currently they both have same name databases but different urls, so can be easily swapped in config.

**Comment by 9600** [comment]
A name other than "limemicro" would be good, as we may well have DBs related to other projects and so this is extremely ambiguous. If having a -prod suffix complicates things let's just go with "limescan".

**Comment by ShaneHudson** [comment]
Went with "limescan"
